os: Visual Studio 2017

environment:
    BOOST_ROOT: C:\Libraries\boost_1_64_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib64-msvc-15
    CMAKE_PREFIX_PATH: C:\Qt\5.12.1\msvc2017_64

install:
    - git submodule update --init --recursive

build_script:
    - md build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" ..
    - cmake --build . --config Release
