language: cpp

matrix:
  include:
      - os: linux
        dist: xenial
        sudo: required
        env:
            - CMAKE_GENERATOR_NAME="Unix Makefiles"
            - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
            - Qt5_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5"
      - os: osx
        osx_image: xcode10.1
        env:
            - CMAKE_GENERATOR_NAME="Unix Makefiles"
            - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
            - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - qtbase5-dev
            - lcov
        sources:
            - ubuntu-toolchain-r-test
    homebrew: # macOS
        packages:
            - cmake
            - git
            - qt5

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build
    - cd ./build
    - cmake -G "$CMAKE_GENERATOR_NAME" -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME ..
    - cmake --build . --config Release
    - cmake --build . --config Release --target package

after_success:
    # Create lcov report
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
    - lcov --list coverage.info # debug info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"